image: registry.gitlab.com/brinkervii/grapejuice-ci-image/master

grapejuice:test:
    stage: test
    script:
        - export PYTHONPATH=$(pwd)/src
        - virtualenv -p $(which python3) ./venv
        - source ./venv/bin/activate
        - pip install -r requirements.txt
        - pip install -r dev_requirements.txt
        - pytest tests

grapejuice:install_debian:
    stage: test
    script:
        - find artifacts -iname \*.dev -exec sudo apt install ./{} \;

grapejuice:debian:
    stage: build
    artifacts:
        expire_in: 1 year
        paths:
            - artifacts/
    script:
        - virtualenv -p $(which python3) ./venv
        - source ./venv/bin/activate
        - pip install -r requirements.txt
        - python3 setup.py package_debian
        - mkdir artifacts
        - cp dist/debian/* artifacts
