image: registry.gitlab.com/brinkervii/grapejuice-ci-image/master

grapejuice:test:
    stage: test
    script:
        - export PYTHONPATH=$(pwd)/src
        - pipenv install --dev
        - pipenv run pytest tests
