image: registry.gitlab.com/brinkervii/grapejuice-ci-image/master

grapejuice:test:
    stage: test
    script:
        - export PYTHONPATH=$(pwd)/src
        - pipenv install --dev --python $(which python3)
        - pipenv run pytest tests

grapejuice:linux_package:
    stage: deploy
    artifacts:
        expire_in: 30 days
        paths:
            - artifacts/
    script:
        - export PYTHONPATH=$(pwd)/src
        - pipenv install --dev --python $(which python3)
        - pipenv run python3 -m grapejuice_packaging linux_package --dist-dir artifacts
